version: "3.5"

services:
  web_build:
    build: ../
    container_name: "upc_pay_pe_build"
    volumes:
      - dist:/usr/src/app/dist
  web:
    image: nginx
    ports:
      - 80:80
    container_name: "upc_pay_pe_web"
    restart: always
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  dist: